juspay/services-flake

nix/postgres.nix
=> postgres: add defaultSettings internal option

nix/postgres.nix
useful if one wishes to set it to something othar than $USER (pg default)
=> feat(postgres): add superuser option

README.md, nix/default.nix, nix/elasticsearch.nix, nix/elasticsearch_test.nix, test/flake.nix
=> Add elasticsearch service

.github/workflows/ci.yaml
=> MacOS (`x86_64-darwin`) CI

README.md, example/flake.nix, nix/default.nix, nix/mysql.nix, nix/mysql_test.nix, test/flake.nix
Resolves #21 
Question:
- Should we base our mysql service on https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/databases/mysql.nix?
TODO:
=> Add MySQL service

.github/workflows/ci.yaml
=> magic-nix-cache

.github/workflows/ci.yaml, dev/flake.lock, flake.nix
=> nixci: upgrade to 0.2

README.md
The existing template is a pretty great and self explanatory starting point
=> docs: getting started using template

README.md
Discussions about this project will happen here.
=> Project Zulip

nix/default.nix, nix/nginx.nix, nix/nginx_test.nix, test/flake.nix
=> Add nginx service

doc/services-flake/clickhouse.md, doc/services-flake/services.md, nix/clickhouse.nix, nix/clickhouse_test.nix, nix/default.nix, test/flake.nix
=> Add Clickhouse service

nix/redis-cluster.nix
=> `redis-cluster`: run create cluster only if it is not initialised

doc/clickhouse.md, nix/clickhouse/clickhouse_test.nix, nix/clickhouse/default.nix
=> change clickhouse `extraConfig` type to yaml

nix/postgres/setup-script.nix
=> postgres init: use -U ${config.superuser} with psql if superuser != null

doc/cassandra.md, doc/services.md, nix/cassandra.nix, nix/cassandra_test.nix, nix/default.nix, test/flake.nix
=> cassandra: init service

.github/workflows/ci.yaml
=> ci: Use cachix

README.md, doc/start.md
=> docs: add motivation for creating services-flake

test/overlays/pgadmin.nix
https://github.com/NixOS/nixpkgs/issues/281214
=> test(pgadmin): Link to upstream bug

test/overlays/grafana.nix
https://github.com/NixOS/nixpkgs/issues/273998
Resolves #128
=> test(grafana): Link to upstream issue

doc/guide.md, doc/guide/datadir.md
Preview:
```sh
nix run "github:juspay/services-flake/guide-datadir?dir=doc"
```
=> docs(guide): dataDir init; unix-domain socket length limitation

CHANGELOG.md, dev/flake.nix, justfile
=> feat(dev): add `just changelog`

nix/mysql/default.nix, nix/mysql/mysql_test.nix
Introduced a new attribute `socketDir` to control the UDS location. If null, defaults to `dataDir` to maintain backward compatibility. Covered with tests.
=> feat(mysql): allow configuring socketDir on mysql

example/llm/flake.lock, flake.nix
=> ci: Build `example/llm` in nixci

example/llm/flake.nix
For details, see:
- https://github.com/juspay/services-flake/issues/230#issuecomment-2171057821
- https://github.com/juspay/services-flake/issues/230#issuecomment-2171060149
- https://github.com/juspay/services-flake/issues/230#issuecomment-2171060331
- https://github.com/juspay/services-flake/issues/230#issuecomment-2171062000
Additionally introduced `WEBUI_SECRET_KEY`, see why: https://github.com/juspay/services-flake/issues/229#issuecomment-2171091889
resolves #229 and #230
=> chore(example/llm): Re-evalute `open-webui` ENVs

nix/postgres/default.nix
cf. https://github.com/juspay/services-flake/blob/dea27be987fb8ad62c3c1454b8c312e01e37832a/nix/postgres/setup-script.nix#L11-L17
=> docs(postgres): Fully document `initialDatabases.schemas`

test/flake.nix
=> chore: Enable `grafana` and `searxng` tests on Darwin

doc/contributing.md, doc/elasticsearch.md, doc/nginx.md, doc/redis-cluster.md, doc/redis.md, doc/zookeeper.md
nix/*_test.nix -> nix/services/*_test.nix
=> Fixed links in usage examples

doc/apache-kafka.md, doc/elasticsearch.md, doc/nginx.md, doc/redis-cluster.md, doc/redis.md, doc/services.md, doc/share-services.md, doc/zookeeper.md
resolves https://github.com/juspay/services-flake/issues/132
=> docs: Remove WIP status from services and add introduction

doc/examples.md, doc/without-flake-parts.md, example/without-flake-parts/flake.lock, example/without-flake-parts/flake.nix, flake.nix
A useful addition that demonstrates more ways to use `services-flake`
=> chore(example/without-flake-parts): init

doc/start.md
Commit 51ecb713515d5310eb0cc446df13547bb7efc917 moved the location of `flake.nix`. This PR adjusts sources to changes.
=> fix: update template flake

README.md
inspired by https://github.com/juspay/hyperswitch/blob/main/README.md#-thanks-to-all-contributors
=> chore(readme): Credit contributors

nix/services/redis.nix
fixes https://github.com/juspay/services-flake/issues/365
=> fix(redis): `unixSocket` logic broken for relative socket paths

doc/minio.md, doc/services.md, nix/services/default.nix, nix/services/minio.nix, nix/services/minio_test.nix, test/flake.nix
Add [MinIO](https://min.io/) service based on [this](https://github.com/cachix/devenv/blob/b6b5b96bd0b669b1f41147cbde950c26085a25c8/src/modules/services/minio.nix) devenv service.
=> Add MinIO service

dev/nix/pre-commit.nix
resolves https://github.com/juspay/services-flake/issues/238
=> ci(formatting): Enable check in project root

doc/share-services.md
=> docs(share-services): init

.github/workflows/ci.yaml
See https://github.com/juspay/omnix/pull/417
=> fix(ci): `omnix` changed arguments handling for `nix`

example/llm/flake.nix
=> chore(example/llm): Disable `process-compose` server

doc/custom-service.md
resolves https://github.com/juspay/services-flake/issues/458
=> docs(custom-service): Fix multi-instance example

nix/services/mysql/default.nix
resolves https://github.com/juspay/services-flake/issues/485
=> fix(mysql): Explicitly pass `my.cnf` path to avoid global fallback

doc/pubsub-emulator.md, doc/services.md, nix/services/default.nix, nix/services/pubsub-emulator.nix, nix/services/pubsub-emulator_test.nix, test/flake.nix
its a bit weird because there is no pubsub emulator package, but a component from google-clioud-sdk pacakge
thats the only part I wasn't sure how to cleanup
=> feat(pubsub-emulator): init service

doc/azurite.md, doc/services.md, nix/services/azurite.nix, nix/services/azurite_test.nix, nix/services/default.nix, test/flake.nix
Adds Azurite as a service
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite
=> azurite: init
