README.md, nix/default.nix, nix/redis.nix, nix/redis_test.nix, test/flake.nix
Resolves #6 
Example:
```nix
{
process-compose."default" = { config, ... }:
{
imports = [
inputs.services-flake.processComposeModules.default
];
services.redis.enable = true;
};
}
```
TODO:
=> Add redis service

.envrc, README.md, dev/flake.nix, test.sh, test/flake.lock, test/flake.nix
Reverts juspay/services-flake#16
Actually, it is better to keep this all _decoupled_ and separate (for simplicity), especially I've arrived at a design for `nixci` where it can/will support building _multiple_ sub-flakes.
=> Revert "dev flake: check example and tests"

flake.nix, test.sh
We're not using it yet, because nixci is yet to be stable.
To test, run `nix run github:srid/nixci` at project root.
=> Add `nixci` config to flake

README.md, dev/flake.lock, dev/flake.nix, example/.envrc, example/flake.nix, example/justfile, justfile
First, this PR switches the dev flake from mission-control to [just](https://github.com/casey/just) similar to https://github.com/srid/haskell-template/pull/111
Then, we introduce `justfile` under the example flake. Now if you do,
```sh
cd ./example
mkdir foo 
cd ./foo
nix run
```
The data directory will be created under `./example/foo` which is unexpected. Whereas, the following would always create it in `./example`:
```sh
cd ./example
mkdir foo 
cd ./foo
just
```
Unless `[no-cd]` is used, [just](https://github.com/casey/just#recipe-parameters) will always cd to the directory where the `justfile` lives. 
The README documents this, as a sufficient solution such that it resolves #26.
=> Use `just` for deterministic `dataDir` in Nix shell

README.md, nix/default.nix, nix/postgres.nix, nix/redis-cluster.nix, nix/redis-cluster_test.nix, test/flake.nix
Closes #15 
`create-cluster` shell script provided by `redis` includes a sub-command to clean all the nodes, which is just removing all the files from the data directory. We can ignore that and maybe just add it under "How to" section in doc.
Example:
```
{
process-compose."default" = { config, ... }:
{
imports = [
inputs.services-flake.processComposeModules.default
];
services.redis-cluster."cluster1".enable = true;
};
}
```
TODO:
=> Add Redis cluster service

.github/workflows/ci.yaml, example/flake.lock, example/flake.nix, justfile, nix/postgres_test.nix, nix/redis-cluster_test.nix, nix/redis_test.nix, test/flake.lock, test/flake.nix
Resolves #32 
Run native test
```bash
just test
```
TODO
=> Process as test (VM -> Native test)

test/flake.nix
This is set by default in `process-compose-flake` after https://github.com/Platonic-Systems/process-compose-flake/pull/42
=> Remove `port = 0;` attribute for test processes

README.md, nix/default.nix, nix/lib.nix, nix/postgres.nix
formatting checks weren't detected in CI, due to: https://github.com/juspay/services-flake/issues/45
=> fmt; add kafka and zk service to readme

example/flake.lock, example/flake.nix, nix/apache-kafka.nix, nix/elasticsearch.nix, nix/mysql.nix, nix/postgres.nix, nix/redis-cluster.nix, nix/redis.nix, nix/zookeeper.nix, test/flake.lock
Closes #46 
Question: Won't it be repetitive to have the process name and namespace present the same info? For instance in the screenshot below, `pg1` and `pg1-init` are grouped together under `pg1` namespace, which is the intended behaviour, but doesn't it look like there are too many `pg1's`.
TODO:
- Use [this](https://github.com/F1bonacc1/process-compose/blob/5d7d23deca386ea456d76effb594a7c326643375/README.md?plain=1#L683-L686) to create a small clip and demonstrate how to start selective namespaces, when others aren't needed.
=> Namespaces

example/flake.lock, test/flake.lock
Primarily for: Starting processes of specific namespace using [`-n`](https://github.com/F1bonacc1/process-compose/blob/5d7d23deca386ea456d76effb594a7c326643375/README.md?plain=1#L683-L686)
=> process-compose: 0.60.0 -> 0.65.1

nix/postgres/default.nix
=> Postgres: Added option depends_on

example/flake.nix, nix/postgres/default.nix, nix/postgres/postgres_test.nix, nix/postgres/setup-script.nix
`initialDumps` is always created under `postgres` database, which is not a desirable default behaviour when your dumps are intended for different database, like [`atlas_dev` in nammayatri](https://github.com/nammayatri/nammayatri/blob/2e20e20b89591501b32743c4cfe52b24dd1aabda/Backend/nix/arion-configuration.nix#L49).
We already have [schema](https://github.com/juspay/services-flake/blob/2211042f3e04de6b105f8d70c0be6213a2127d88/nix/postgres/default.nix#L207-L214) module option to load a schema into a given [database name](https://github.com/juspay/services-flake/blob/2211042f3e04de6b105f8d70c0be6213a2127d88/nix/postgres/default.nix#L201-L206). The schema module option already supports loading from either a file or all the [`.sql` files in a …
=> [Postgres]: Use `schemas` in-place of `initialDumps`

nix/apache-kafka.nix, nix/apache-kafka_test.nix
Additionally, rebased the options configuration from [upstream nixos module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/apache-kafka.nix).
Resolves #72
=> [apache-kafka] Fix the configuration to allow kafka to run on non-default port

.github/workflows/ci.yaml
The DetSys installer installs bleeding edge Nix, triggering https://github.com/srid/nixci/issues/35
Let's just use the "tried and true" https://github.com/cachix/install-nix-action where Nix is not upgraded behind the scenes over time (as long as we use Git tags).
=> ci: Don't upgrade Nix behind the scenes

example/flake.nix, nix/postgres/default.nix, nix/postgres/postgres_test.nix
On the first run, when `data` directory doesn’t exist, both the `init` processes (`pg1-init` and `pg2-init`) will try to create the `data` directory and one of them fails, leading to one of the server not starting. To solve this, `pg2-init` can depend on `pg1-init` completing.
Also `depends_on` option added to postgres [here](https://github.com/juspay/services-flake/pull/71), will not be needed because we can do it as demonstrated in `example/flake.nix` and `nix/postgres/postgres_test.nix` (check the diff). This keeps the definition of `depends_on` in one-place.
Resolves #74
=> [Postgres]: Fix `test` process not starting

nix/postgres/default.nix, nix/postgres/setup-script.nix
* Postgres: Fix a build failure when initialDatabase schema is null
* Postgres: Add a socketDir config option which defaults to config.dataDir and allows customization of socketDir for users who do not wish it fixed to dataDir
* Also, sockets are limited to around [100 chars](https://linux.die.net/man/7/unix)
* In the case that the default or desired dataDir absolute path exceeds this char limit, postgres will fail to start if it is also used for socketDir
* In this case, dataDir can remain as desired and socketDir can be set separately to a shorter absolute path
=> postgres: add socketDir option

nix/postgres/postgres_test.nix, nix/postgres/setup-script.nix
* Ensure postgres socketDir mktemp initialization succeeds when the socketDir path does not exist yet
* See https://github.com/juspay/services-flake/pull/77#discussion_r1458072831
* Add a test for socketDir configured with a multi-level non-existing path
=> postgres ensure socketDir mktemp init succeeds

doc/services-flake/clickhouse.md
Emanote uses the first paragraph as page description, thus it is useful to write that paragraph reflecting the description of that page. Without this PR, link previews look like this:
^ which is not the correct description for the page.
=> docs/clickhouse: add intro

doc/flake.lock, doc/services-flake/clickhouse.md
See https://emanote.srid.ca/guide/markdown#hanchor
This allows us to link to the individual sections using shorter links. It'd be good to follow this convention throughout other docs.
=> docs/clickhouse: Use heading anchors

nix/postgres/setup-script.nix
If the socketDir is in `tmpfs`, or if it is deleted by some other process, we would want the `socketDir` to be created, if not already present, on restarts.
=> postgres: always create `socketDir` during `init` if not already present 

test/flake.nix
This fixes,
```
error: access to absolute path '/nix/store/nix/apache-kafka_test.nix' is forbidden in pure eval mode (use '--impure' to override)
```
Seems to happen with newer Nix versions. See https://github.com/juspay/services-flake/pull/94#issuecomment-1937474878
=> test: Fix impure access of parent paths

.github/workflows/ci.yaml
Reverts juspay/services-flake#79
To fix, https://github.com/srid/nixci/issues/35
Also, introduces Garnix cache to speed up fetching of nixci.
=> Revert "ci: Don't upgrade Nix behind the scenes"

.gitignore, dev/flake.nix, justfile
This is useful, as with the increasing number of services one might want to test only the service that they are making changes to.
**Note:** Here we are using `nix build` to test specific services as `nix flake check` doesn’t support running individual checks, see: https://github.com/NixOS/nix/issues/8881.
=> just: test specific service

dev/flake.lock, dev/flake.nix, flake.nix, test/flake.nix
specifying `projectRoot` in `treefmt` fixes #45 
```
treefmt-check> treefmt 0.6.1
treefmt-check> [INFO ] #nixpkgs-fmt: 26 files processed in 31.84ms
treefmt-check> 0 files changed in 37ms (found 42, matched 26, cache misses 26)
treefmt-check> On branch main
treefmt-check> nothing to commit, working tree clean
```
=> explicitly define project root in treefmt

nix/clickhouse/default.nix
previously, was shallow merge to append extra configs, which would have removed some configs. updated to use `lib.recursiveUpdate` to deep merge extraConfig.
=> clickhouse: use `lib.recursiveUpdate` to deep merge extraConfig

doc/contributing.md, doc/index.md
As of now contributing is no longer a child of services-flake (see https://community.flake.parts/services-flake):
After this change, contributing will appear after `Getting started` in the sidebar:
=> Doc: add `contribuiting` doc to index; set order of `contributing` to -9

.github/workflows/ci.yaml
Trying out https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> ci: Add m1 runner to matrix

doc/pgadmin.md, doc/services.md, nix/default.nix, nix/pgadmin.nix, nix/pgadmin_test.nix, test/flake.nix
resolves #80 
**Related issues**
- https://github.com/NixOS/nixpkgs/issues/281214
=> add pgAdmin service

.gitignore, dev/flake.lock, dev/flake.nix, dev/nix/pre-commit.nix
with treefmt and commitizen enabled
=> Add pre-commit-hooks.nix, enforcing conventional commits

doc/contributing.md
Rebase this PR after #121 gets merged.
I used `docs:` in commit message, because:
https://www.conventionalcommits.org/en/v1.0.0/#summary
=> docs: Fix nix shell command

doc/flake.lock, doc/flake.nix, doc/index.yaml, justfile
This enables us to preview the whole community.flake.parts (live server or static site) in the context of the local docs (./doc).
Uses https://github.com/flake-parts/community.flake.parts/pull/52
=> chore(docs): Use cfp module

README.md, doc/index.md
- `Guide` page is not a child of `services-flake` in <https://community.flake.parts> page:
- Link to a more detailed datadir documentation in README
=> docs: (readme) link to `datadir` doc from `cfp`; (index) add guide

nix/default.nix, nix/mysql/default.nix, nix/mysql/mysql_test.nix, nix/mysql/test_schemas/bar.sql, nix/mysql/test_schemas/baz.md, nix/mysql/test_schemas/foo.sql, test/flake.nix
* mysql service would assume that all the `*.sql` files in the directory, provided by `initialDatabases [{ schema = <directory>; ... }]`, exists in a folder named [mysql-databases](https://github.com/juspay/services-flake/blob/291e7be83aa0f24b8e40fc61df4a895827788707/nix/mysql.nix#L239-L241), after this change it would just look for all the `*.sql` files in the top-level schema directory.
* add tests
=> fix(mysql)!: look for `*.sql` files in the top-level schema directory

nix/apache-kafka.nix, nix/cassandra.nix, nix/clickhouse/default.nix, nix/elasticsearch.nix, nix/mysql/default.nix, nix/nginx.nix, nix/prometheus.nix, nix/redis-cluster.nix, nix/redis.nix, nix/zookeeper.nix
Provides us with following benefits:
- use `runtimeInputs` instead of manually exporting `PATH`
- get shellcheck by default
=> refactor: writeShellScriptBin -> writeShellApplication

doc/postgresql.md, nix/postgres/default.nix, nix/postgres/setup-script.nix
resolves #139 
the solution is implemented based on https://github.com/juspay/services-flake/issues/139#issuecomment-1998114104
An empty `socketDir` would mean that by default the `postgres` service will use TCP/IP instead of Unix-domain sockets.
=> fix(postgres): empty `socketDir` by default

test/flake.lock, test/nix/pkgs.nix
fixed here: https://github.com/NixOS/nixpkgs/pull/297968
Also, hydra-checks pass on all four platforms:
```sh
shivaraj in 🌐 nixos in ~
❯ nix run github:nix-community/hydra-check -- grafana --arch aarch64-darwin
Build Status for grafana.aarch64-darwin on jobset nixpkgs/trunk
✔ grafana-10.4.1 from 2024-03-27 - https://hydra.nixos.org/build/254421303
shivaraj in 🌐 nixos in ~ took 45s
❯ nix run github:nix-community/hydra-check -- grafana --arch x86_64-darwin
Build Status for grafana.x86_64-darwin on jobset nixpkgs/trunk
✔ grafana-10.4.1 from 2024-03-27 - https://hydra.nixos.org/build/254422747
shivaraj in 🌐 nixos in ~
❯ nix run github:nix-community/hydra-check -- grafana --arch x86_64-linux
Build Status for nixpkgs.grafana.x86_64-linux on jobset nixos/trunk-combined
✔ grafana-10.4.0 from …
```
=> fix(test): grafana on darwin is no longer broken in upstream

nix/pgadmin.nix
Hey, just a little fix for mac:
`readlink -m` is invalid on mac. Added coreutils as a runtime input for darwin.
Other scripts in the repo have a similar issue (using the -m flag for e.g.) but I am not using them atm so cannot QA very well.
=> Fix pgadmin scripts on MacOS

nix/grafana.nix
`readlink` shipped by default in macOS doesn't support `-m` flag
=> fix(grafana): add `coreutils` as runtimeInput for the startScript

nix/postgres/default.nix, nix/postgres/postgres_test.nix
This PR resolves the issue where `pg_isready` would fail when `socketDir` is set and `listen_addresses` is empty. `pg_isready` is now modified to use `socketDir` when it is available.
=> fix(postgres): fix pg_isready issue with empty listen_addresses

.github/workflows/update-flake-lock-ex-share-services.yaml, .github/workflows/update-flake-lock-ex-simple.yaml, .github/workflows/update-flake-lock-test.yaml
=> ci: add `update-flake-lock` cron jobs for `example-{simple, share-services}` and `test`

nix/mysql/default.nix, nix/mysql/mysql_test.nix
The change fixes #169. Tested locally. To reproduce the original issue just try to spin up a local mysql service using `nixpkgs-old.legacyPackages.mysql57` package while `mysqld.default-time-zone` or `importTimeZones` is set.
=> fix: use absolute socket path in configureTimezones. this fixes #169

nix/postgres/setup-script.nix
resolves #207 
From psql docs (https://www.postgresql.org/docs/current/app-psql.html):
> psql returns 0 to the shell if it finished normally, 1 if a fatal
error of its own occurs (e.g., out of memory, file not found), 2 if the connection to the server went bad and the session was not interactive, and 3 if an error occurred in a script and the variable ON_ERROR_STOP was set.
Also resolves https://github.com/juspay/services-flake/issues/107
=> fix(postgres): stop init on error in `sql` scripts

nix/grafana.nix, nix/grafana_test.nix
Addresses juspay/services-flake#210.
I've tested this by hand with configuration:
```nix
services.grafana."grafana" = {
enable = true;
providers = [
{
name = "Databases";
type = "file";
options = {
path = ./dashboards;
foldersFromFilesStructure = true;
};
}
];
};
```
I haven't looked into it, but it might be possible to extend the existing Grafana test to check that a folder of dashboards is loaded.
=> feat(grafana): add providers configuration

doc/ollama.md, nix/default.nix, nix/ollama.nix, nix/ollama_test.nix, test/flake.nix
ported from https://github.com/shivaraj-bh/ollama-flake/blob/main/services/ollama.nix
TODO
=> feat(ollama): init

doc/open-webui.md, doc/services.md, example/llm/flake.nix, nix/default.nix, nix/ollama.nix, nix/open-webui.nix, nix/open-webui_test.nix, test/flake.nix
ported from: https://github.com/shivaraj-bh/ollama-flake/blob/main/services/open-webui.nix
This was also recently upstreamed to [nixpkgs](https://github.com/NixOS/nixpkgs/tree/master): https://github.com/NixOS/nixpkgs/pull/316248
TODO:
=> feat(open-webui): init

example/llm/flake.lock, example/llm/flake.nix
Hi!
I separated everything into small commits for easier review.
Let me know what you think!
=> example/llm: minor refactor

doc/searxng.md, example/llm/flake.nix, nix/default.nix, nix/searxng.nix, nix/searxng_test.nix, test/flake.nix
This PR:
Test with:
```nix
{
inputs = {
nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
flake-parts.url = "github:hercules-ci/flake-parts";
systems.url = "github:nix-systems/default";
process-compose-flake.url = "github:Platonic-Systems/process-compose-flake";
services-flake.url = "github:juspay/services-flake";
};
outputs =
inputs:
inputs.flake-parts.lib.mkFlake { inherit inputs; } {
systems = import inputs.systems;
imports = [ inputs.process-compose-flake.flakeModule ];
perSystem =
{ pkgs, lib, ... }:
{
process-compose."default" =
pc:
let
inherit (pc.config.services.searxng.searxng) host port;
in
{
imports = [ inputs.services-flake.processComposeModules.default ];
services.searxng."searxng" = {
enable = true;
settings = {
use_default_settings = true;
server.secret_key = "secret"; …
```
=> searxng: init

dev/flake.nix
As a workaround for #238 until we have a proper fix.
=> chore(dev): Re-enable treefmt-nix flake check

nix/apache-kafka.nix, nix/cassandra.nix, nix/clickhouse/default.nix, nix/elasticsearch.nix, nix/grafana.nix, nix/lib.nix, nix/mysql/default.nix, nix/nginx/default.nix, nix/ollama.nix, nix/open-webui.nix, nix/pgadmin.nix, nix/postgres/default.nix, nix/prometheus.nix, nix/redis-cluster.nix, nix/redis.nix, nix/searxng.nix, nix/tempo.nix, nix/weaviate.nix, nix/zookeeper.nix
=> refactor: Do not repeat `dataDir`

doc/tika.md, nix/services/default.nix, nix/services/searxng.nix, nix/services/tika.nix, nix/services/tika_test.nix, test/flake.nix
Tika has been merged today (https://github.com/NixOS/nixpkgs/pull/279059) so we need to wait 2~3 days until it become available here.
Once there, I'll set this PR in Ready for review.
=> service/tika: init

nix/services/tika.nix
Following `nixpkgs` PR @ https://github.com/NixOS/nixpkgs/pull/327886, this PR add the `enableOcr` option.
=> tika: add `enableOcr` option

nix/services/apache-kafka.nix, nix/services/cassandra.nix, nix/services/clickhouse/default.nix, nix/services/elasticsearch.nix, nix/services/grafana.nix, nix/services/mysql/default.nix, nix/services/nginx/default.nix, nix/services/ollama.nix, nix/services/open-webui.nix, nix/services/pgadmin.nix, nix/services/postgres/default.nix, nix/services/prometheus.nix, nix/services/redis-cluster.nix, nix/services/redis.nix, nix/services/searxng.nix, nix/services/tempo.nix, nix/services/tika.nix, nix/services/weaviate.nix, nix/services/zookeeper.nix
=> feat: Add `max_restarts` to all services to avoid restarting indefinitely

nix/services/elasticsearch.nix, nix/services/elasticsearch_test.nix
=> elasticsearch: copy plugins to `dataDir`

nix/services/elasticsearch.nix
We need to add the write permission to directories in elasticsearch plugins, not execute, which they already have.
Sorry @shivaraj-bh this was a typo in my suggestion in #331
=> fix(elasticsearch): Fixed permission to add to directories in elasticsearch plugins

nix/lib.nix, nix/services/apache-kafka.nix, nix/services/cassandra.nix, nix/services/clickhouse/default.nix, nix/services/elasticsearch.nix, nix/services/grafana.nix, nix/services/memcached.nix, nix/services/mysql/default.nix, nix/services/nginx/default.nix, nix/services/ollama.nix, nix/services/open-webui.nix, nix/services/pgadmin.nix, nix/services/postgres/default.nix, nix/services/prometheus.nix, nix/services/redis-cluster.nix, nix/services/redis.nix, nix/services/searxng.nix, nix/services/tempo.nix, nix/services/tika.nix, nix/services/weaviate.nix, nix/services/zookeeper.nix
=> refactor: consolidate all settings in `defaultProcessSettings`

doc/mongodb.md, doc/services.md, nix/services/default.nix, nix/services/mongodb.nix, nix/services/mongodb_test.nix, test/flake.nix
Adds support for running MongoDB, based off the Redis workflow.
=> feat: Add support for mongodb

doc/devshell.md, doc/guide.md, example/share-services/northwind/flake.nix, example/share-services/pgweb/flake.nix, example/simple/flake.nix, nix/services/default.nix, nix/services/devshell.nix
=> feat: Provide a `devShell` with packages from enabled services

nix/services/redis.nix, nix/services/redis_test.nix
=> feat(redis): Support using Unix socket

doc/redis.md
=> docs(redis): Document `port` and `unixSocket` options

doc/mongodb.md, nix/services/mongodb.nix, test/flake.nix
`mongodb-ce` fetches pre-built binaries.
The previously used `mongodb` package had to be built from scratch because of license restrictions, see: https://github.com/juspay/services-flake/pull/339#issuecomment-2377968085
=> chore(mongodb): Use `mongodb-ce`; Enable test on `darwin`

.github/workflows/ci.yaml, dev/flake.lock, dev/flake.nix
This is the first step towards demonstrating `om hack` (via direnv) for this project.
=> chore(ci): Setup cachix

nix/lib.nix, nix/services/apache-kafka.nix, nix/services/cassandra.nix, nix/services/clickhouse/default.nix, nix/services/elasticsearch.nix, nix/services/grafana.nix, nix/services/memcached.nix, nix/services/mysql/default.nix, nix/services/nginx/default.nix, nix/services/ollama.nix, nix/services/open-webui.nix, nix/services/pgadmin.nix, nix/services/postgres/bad_test.sql, nix/services/postgres/default.nix, nix/services/postgres/postgres_test.nix, nix/services/postgres/setup-script.nix, nix/services/prometheus.nix, nix/services/redis-cluster.nix, nix/services/redis.nix, nix/services/searxng.nix, nix/services/tempo.nix, nix/services/tika.nix, nix/services/weaviate.nix, nix/services/zookeeper.nix, test/flake.lock, test/flake.nix
This reverts commit 1e682a85c4dbc98cad8e2a940e1759a66941df58.
For context, see https://github.com/juspay/services-flake/pull/348#issuecomment-2440039987
TODO:
=> Revert "refactor: consolidate all settings in `defaultProcessSettings` (#348)"

nix/services/clickhouse/bad_test.sql, nix/services/clickhouse/clickhouse_test.nix, nix/services/clickhouse/default.nix
=> fix(clickhouse-init): kill `clickhouse-server` on `EXIT`

dev/flake.lock, dev/flake.nix, dev/nix/pre-commit.nix, justfile
We already use pre-commit and that supports nixpkgs-fmt.
cf. https://github.com/srid/haskell-template/pull/144
Also, this PR updates git-hooks.nix while making a non-flake thereby reducing the number of lock file (`dev/flake.lock`) entries.
=> chore(nix): Remove treefmt

doc/nats-server.md, doc/services.md, nix/services/default.nix, nix/services/nats-server.nix, nix/services/nats-server_test.nix, test/flake.nix
Service for https://github.com/nats-io/nats-server
=> feat(nats-server): Add service

test/flake.nix
Fails on macOS with: 
```sh
error: chmod '"/nix/store/rcx3n94ygmd61rrv2p22sykhk0yx49n4-elasticsearch-7.17.16/modules/x-pack-ml/platform/darwin-aarch64/controller.app"': Operation not permitted
```
Related: https://github.com/NixOS/nix/issues/6765
=> chore(test): disable elasticsearch on darwin

example/llm/flake.nix, flake.nix, nix/process-compose/default.nix, nix/process-compose/defaults.nix, test/flake.nix
=> feat: Add process-compose `defaults` module

nix/services/mysql/default.nix, nix/services/mysql/mysql_test.nix
MySQL service rejected DB names containing “-”, although MariaDB allows them. Fixes #513
=> fix(mysql): allow hyphens in database names

doc/phpfpm.md, doc/services.md, nix/services/default.nix, nix/services/phpfpm.nix, nix/services/phpfpm_test.nix, test/flake.nix
I wanted to run WordPress via process compose and had to add phpfpm to achieve this. It is mainly based on the [NixOS module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/phpfpm/default.nix), but simplified a bit.
=> feat: add support for phpfpm

nix/services/postgres/setup-script.nix
Wrapped `PGHOST` with `"` for `unix_socket_directories.
Resolves #532.
| Initial | After |
|---------|-------|
| ![Screenshot 2025-06-06 at 15 09 18](https://github.com/user-attachments/assets/68ef8778-6c6c-4825-82b0-0a61fbde9d6b) | ![Screenshot 2025-06-06 at 15 12 47](https://github.com/user-attachments/assets/b314f765-89c3-4365-a72b-1d964172362f) |
In the Initial image the error is because of the asbsolute path getting broken into 2 argsuments.
```sh
pg_ctl -D ./data/pg2 -w start -o '-c unix_socket_directories=/Users/nikhil.singh/work/services flake/test/test/new/ socket/path/pg-init-m2GRBV -c listen_addresses= -p 5433'
waiting for server to start....postgres: invalid argument: "flake/test/test/new/socket/path/pg-init-m2GRBV"
Try "postgres --help" for more information.
```
Where as in …
=> fix(postgres): Quote `unix_socket_directories` argument

nix/services/phpfpm.nix, nix/services/phpfpm_test.nix
Add a "settings" option to the phpfpm module.
This allows changing global settings such as
the logging level.
The existing "extraConfig" option sets the pool
settings, but cannot set global settings.
The option name "settings" is taken from the
NixOS Module.
=> feat: Add global settings option to phpfpm

nix/services/phpfpm.nix
When the total environment is too large, such as
over 8KB, FastCGI closes the connection with
no output or log messages. cgi-fcgi returns with
an exit code of 104 and no output.
This happens even when clear_env is set in the
PHP-FPM config, since the problem seems to happen
before that would be applied.
To fix this, we prefix the cgi-fcgi command with
`env -i` to clear the environment.
=> fix(phpfpm): Health checks fails when env is large
